name: Run Intraday Option Model

on:
  schedule:
    - cron: '40 4 * * *'   # 10:10 AM IST
    - cron: '43 4 * * *'   # 10:13 AM IST
    - cron: '45 4 * * *'   # 10:15 AM IST
  workflow_dispatch:        # allows manual run
  push:                      # Runs on every push

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Option Strategy Script
        run: python Option_Intraday_ml_model.py
