name: Run Intraday Option Model

on:
  schedule:
    - cron: '0 4 * * 1-5'     # 09:30 IST
    - cron: '15 4 * * 1-5'    # 09:45 IST
    - cron: '30 4 * * 1-5'    # 10:00 IST
    - cron: '45 4 * * 1-5'    # 10:15 IST
    - cron: '0 5 * * 1-5'     # 10:30 IST
  workflow_dispatch:        # allows manual run
  push:                      # Runs on every push

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Option Strategy Script
        env:
          TELEGRAM_SECRET_TOKEN: ${{ secrets.TELEGRAM_SECRET_TOKEN }}
        run: python Option_Intraday_ml_model.py
