name: Run Intraday Option Model

on:
  schedule:
    - cron: '*/15 3-10 * * 1-5' #9:15 AM – 3:30 PM
  workflow_dispatch:        # allows manual run
  push:                      # Runs on every push

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Option Strategy Script
        env:
          TELEGRAM_SECRET_TOKEN: ${{ secrets.TELEGRAM_SECRET_TOKEN }}
        run: python Option_Intraday_ml_model.py
